import assert from'node:assert/strict';import fs from'node:fs';import{execFileSync,spawn}from'node:child_process';import{browser}from'./cdp.mjs';import{verifyExtensionSource}from'./verify-extension-source.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const native=(...a)=>execFileSync('python3',['scripts/native-input.py',...a],{encoding:'utf8'});const key=s=>native('gesture',s,'0');const hold=(s,ms)=>new Promise((resolve,reject)=>{const p=spawn('python3',['scripts/native-input.py','gesture',s,String(ms)]);p.on('exit',c=>c?reject(Error('Native input failed '+c)):resolve());});const visible=()=>JSON.parse(native('windows')).some(w=>w.kCGWindowName==='Plico Navigator');
const b=await browser();let api,wid;
try{
 const worker=(await b.call('Target.getTargets')).targetInfos.find(t=>t.type==='service_worker'&&t.url.includes('baedceam'));const{sessionId}=await b.call('Target.attachToTarget',{targetId:worker.targetId,flatten:true});await verifyExtensionSource(b,sessionId);
 api=async expression=>{const r=await b.call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},sessionId);if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};
 const w=await api("chrome.windows.create({url:['https://example.org/#plico-edit-fixture','https://example.com/#plico-edit-peer'],focused:true})");wid=w.id;const [tab,peer]=w.tabs.map(t=>t.id);await api(`chrome.tabs.update(${tab},{active:true})`);native('activate');await sleep(450);
 const t=(await b.call('Target.getTargets')).targetInfos.find(t=>t.url==='https://example.org/#plico-edit-fixture');const p=(await b.call('Target.attachToTarget',{targetId:t.targetId,flatten:true})).sessionId;
 const page=async expression=>{const r=await b.call('Runtime.evaluate',{expression,returnByValue:true},p);if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};
 await page("document.body.innerHTML='<textarea id=fixture>abc</textarea><div style=height:3000px></div>';window.fixtureToken=crypto.randomUUID();window.fixtureTick=0;setInterval(()=>fixtureTick++,100);fixture.focus();fixture.setSelectionRange(3,3)");await sleep(150);
 const token=await page('fixtureToken');let report=[];
 let run=hold('cmd+,wait',600);await sleep(300);assert(!visible(),'Bare Command must not reveal over focused text input');await run;report.push('bare Command preserves page editor');
 key('cmd+,123');await sleep(80);assert.equal(await page('fixture.selectionStart'),0);assert.equal((await api(`chrome.tabs.query({windowId:${wid},active:true})`))[0].id,tab);report.push('Command+Left remains caret navigation in editor');
 await page('fixture.setSelectionRange(3,3)');key('cmd+,51');await sleep(100);assert.equal(await page('fixture.value'),'');assert.equal((await api(`chrome.tabs.query({windowId:${wid}})`)).length,2);report.push('Command+Backspace edits text without closing/navigating');
 await page("fixture.value='abc';fixture.setSelectionRange(1,2)");key('cmd+,11');assert(visible());key('124');key('53');assert.equal(await page('fixtureToken'),token);assert.equal(await page('fixture.value'),'abc');assert.deepEqual(await page('[fixture.selectionStart,fixture.selectionEnd]'),[1,2]);assert(await page('fixtureTick')>0);report.push('explicit navigator/cancel preserves page identity, form and selection');
 await page('fixture.blur()');await sleep(100);run=hold('cmd-right+,37,wait',400);await sleep(220);assert.equal((await api(`chrome.tabs.query({windowId:${wid},active:true})`))[0].id,tab);await run;await sleep(160);assert.equal((await api(`chrome.tabs.query({windowId:${wid},active:true})`))[0].id,peer);report.push('right Command defers activation until release');
 key('ctrl-right+,48');await sleep(160);assert.equal((await api(`chrome.tabs.query({windowId:${wid},active:true})`))[0].id,tab);report.push('right Control MRU switches on release');
 const result={at:new Date().toISOString(),passed:report};fs.writeFileSync('.local/editing-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{if(wid&&api)await api(`chrome.windows.remove(${wid}).catch(()=>{})`).catch(()=>{});b.close();}
